# See the following for documentation:
# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
# https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/lambda_edge/template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: deno.land

Resources:
  DenoLandCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:996721126982:certificate/17ec3785-d60f-46af-837f-fbeefdb31203"
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: DenoLandOrigin
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref DenoLandFunction.Version
          ForwardedValues:
            QueryString: true
          ViewerProtocolPolicy: allow-all
        Origins:
          - Id: DenoLandOrigin
            DomainName: "deno.land.s3-website-us-east-1.amazonaws.com"
            S3OriginConfig: {}

  DenoLandFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Role: !GetAtt DenoLandRoll.Arn
      AutoPublishAlias: live

  DenoLandRoll:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action: 
              - "sts:AssumeRole"
            Principal:
              Service: 
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"

Outputs:
  DenoLandFunction:
    Description: DenoLandFunction ARN
    Value: !GetAtt DenoLandFunction.Arn
  DenoLandCloudFront:
    Description: DenoLandCloudFront DomainName
    Value: !GetAtt DenoLandCloudFront.DomainName
