# See the following for documentation:
# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: deno.land

Resources:
  DenoLandFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Events:
        DenoLand:
          Type: Api
          Properties:
            Path: /x
            Method: get
  DenoLandCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
      Enabled: true
      DefaultRootObject: index.html
      Origins:
        - Id: DenoLandOrigin
          DomainName: deno.land.s3-website-us-east-1.amazonaws.com
          ViewerCertificate:
            AcmCertificateArn: "arn:aws:acm:us-east-1:996721126982:certificate/17ec3785-d60f-46af-837f-fbeefdb31203"
            MinimumProtocolVersion: TLSv1.1_2016
            SslSupportMethod: sni-only
      DefaultCacheBehavior:
        TargetOriginId: DenoLandOrigin
        LambdaFunctionAssociations:
        - EventType: origin-request
          LambdaFunctionARN: !Ref DenoLandFunction.Version
